# Required properties
sonar.projectKey=${env.SONAR_APPNAME}
# sonar.externalIssuesReportPaths=/usr/src/app/horusec_analysis.json

# Source code configuration
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Language-specific settings - use LCOV format for coverage
sonar.javascript.lcov.reportPaths=/usr/src/app/coverage/lcov.info
sonar.typescript.lcov.reportPaths=/usr/src/app/coverage/lcov.info
sonar.scm.provider=git

# Exclusions
sonar.exclusions=**/*.test.ts,\
  **/*.test.tsx,\
  **/*.test.js,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/*.spec.js,\
  **/node_modules/**,\
  **/coverage/**,\
  **/*.d.ts,\
  **/dist/**,\
  **/build/**

# Test configurations
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,\
  **/*.test.tsx,\
  **/*.test.js,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/*.spec.js
sonar.test.exclusions=**/node_modules/**,\
  **/coverage/**

# Coverage exclusions
sonar.coverage.exclusions=**/__mocks__/**, \
  **/*.d.ts,\
  **/*.spec.js,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/*.styled.ts,\
  **/*.styled.tsx,\
  **/*.test.js,\
  **/*.test.ts,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/build/**,\
  **/coverage/**,\
  **/dist/**,\
  **/node_modules/**,\
  **/public/**, \
  **/themes/**
